#!/bin/sh

RADIO_IFACE=$(uci get openwisp_netcheck.radio_iface.name)
VPN_IFACE=$(uci get openwisp_netcheck.vpn_iface.name)
INTERVAL=$(uci get openwisp_netcheck.interval.time)

net_watchdog() {
	if [ -h "/sys/class/net/$RADIO_IFACE" ]; then
                _ssid_status=1
        else
                _ssid_status=0
        fi

	if [ -h "/sys/class/net/$VPN_IFACE" ]; then
		_net_status=0
	else
	        _net_status=1
	fi

}

# Network check loop
while :

do

net_watchdog

	if [[ "$_net_status" -eq "0" && "$_ssid_status" -eq "1" ]]; then
		.$PROG_DIR/owf2_management_off
		_ssid_status=0
		logger	-s "Management SSID down" \
			-t openwisp-netcheck \
			-p daemon.info
		sleep 5

	elif [[ "$_net_status" -eq "1" && "$_ssid_status" -eq "0" ]]; then
		.$PROG_DIR/owf2_management_on
		_ssid_status=1
                logger	-s "Management SSID up" \
			-t openwisp-netcheck \
			-p daemon.info
		sleep 5

	else
		sleep $INTERVAL
	fi

done
