#!/bin/sh /etc/rc.common

START=99

USE_PROCD=1
CONFFILE=/etc/config/openwisp_netcheck
PROG=/usr/sbin/openwisp_netcheck

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn
	procd_set_param file $CONFFILE
	procd_set_param env export PROG_DIR=/usr/sbin/
	procd_close_instance
	logger -s "started" \
	       -t openwisp-netcheck \
	       -p daemon.info
}

stop_service() {
	logger -s "stopping" \
	       -t openwisp-netcheck \
	       -p daemon.info
}
